BaseURL: "https://4ndr0666.github.io/4ndr0site/"
languageCode: "en-us"
title: "4ndr0666 | Online Archive"
theme: "4ndr0line"

params:
  prompt: "4ndr0666@192.168.1.1"
  promptColor: cyan
  promptSimbols: " >"
  promptSimbolsColor: LIME
  startxLocation: "https://4ndr0chat.vercel.app/"
  exitLocation: "/ascii-index.html"
  greetingColor: "white"
  greeting: |
    # -- // LASCIATE OGNE SPERANZA, VOI CH'INTRATE.
  whois:
    name: "4ndr0666"
    alias: "01_dolor.loftier@icloud.com"
    id: "genial_comrade0g@icloud.com"
    id2: "iodine-drawls.0g@icloud.com"
    profession: "Security Architect"
    location: "The Void"
    email: "01_dolor.loftier@icloud.com"
    homelink: "https://4ndr0666.github.io/"
    description: "Online Archive"
  social:
    - name: "MaxUrl"
      url: "https://qsniyg.github.io/maxurl/"
    - name: "icloud+"
      url: "https://www.icloud.com/icloudplus/"
    - name: "Links"
      url: "https://github.com/4ndr0666/Links/blob/main/README.md"
    - name: "GSE"
      url: "https://cse.google.com/cse?cx=07382130c504b4ec9#gsc.tab=0"
    - name: "Upscale"
      url: "https://imageupscaler.com/upscale-image-4x/#start"

  projects:
    - title: "4ndr0base.sh"
      color: LIME
      description: "curl -LO https://github.com/4ndr0666/scr/4ndr0base.sh"
    - title: "Awesome List"
      color: LIME
      link: "https://github.com/stars/4ndr0666/lists/awesome"
    - title: "Netboot.xyz"
      color: RED
      link: "https://github.com/4ndr0666/netboot.xyz-custom"

  misc:
    commandName: scripts
    title: "Pick Your Poison:"
    titleColor: cyan
    content: |
      1. Winutil - Make Windows Not Suck
          Type "irm christitus.com/win | iex" in Admin PowerShell
      2. ChatGPT.sh - Terminal AI
          wget https://gitlab.com/fenixdragao/shellchatgpt/-/raw/main/chatgpt.sh
      3. Micro - Modern Text Editor
          curl https://getmic.ro | bash
